# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build HAP

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch'
        options:
          - haproxy-3.0
          - haproxy 2.8
          - haproxy 2.6
          - haproxy-3.2

jobs:
  build-src:
    name: Build HAProxy
    runs-on: windows-latest

    steps:
      - name: Clone requested version
        id: clone
        run: |
          git clone http://git.haproxy.org/git/${{ inputs.branch }}.git
          cd ${{ inputs.branch }}/
          $version="$(git describe --abbrev=0)"
          $release_name = "$($version)+$([Math]::Floor([decimal](Get-Date(Get-Date).ToUniversalTime()-uformat "%s")))"

          git reset --hard $version

          Write-Host "VARIABLES: $version | ${{ inputs.branch }} | $release_name"

          "release_name=$release_name" >> $env:GITHUB_OUTPUT

      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          platform: x86_64
          packages: make gcc-core gcc-g++ wget libssl-devel zlib-devel libpcre2-devel liblua-devel=5.4.4-1 lighttpd-lua-modules lua=5.4.4-1 cygwin-devel

      - name: Make haproxy (cygwin)
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
        run: |
          cd ${{ inputs.branch }}
          sed -i 's/--export-dynamic/--export-all-symbols/g' Makefile
          make TARGET=cygwin \
            USE_OPENSSL=3.0 \
            USE_SLZ=1 \
            USE_PCRE2=1 USE_PCRE2_JIT=1 \
            USE_LUA=1 LUA_LIB=/usr/lib LUA_INC=/usr/include/lua5.4 LUA_LIB_NAME=lua5.4 \
            USE_THREAD=1 \
            USE_THREAD_DUMP=1 \
            USE_PTHREAD_EMULATION=1 \
            USE_PROMEX=1
            #USE_PRCTL=1 \
            #USE_NETFILTER=1 \
            #USE_NS=1 \
            #USE_LIBCRYPT=1 USE_CRYPT_H=1 \
            #USE_GETADDRINFO=1 \
            #USE_CPU_AFFINITY=1 \
            #USE_DL=1 \
            #USE_EPOLL=1 \
            #USE_BACKTRACE=1 \
            #USE_ACCEPT4=1 \
            #USE_RT=1
            #SHM_OPEN

      - name: Gather artifacts (cygwin)
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -o igncr -eo pipefail '{0}'
        run: |
          mkdir release
          pwd
          ls -al
          ls -al ${{ inputs.branch }}/
          cp ${{ inputs.branch }}/haproxy.exe release/
          dependencies=$(ldd release/haproxy.exe | grep -vi 'system32' | awk '{print $3}')
          for dep in $dependencies; do
              cp "$dep" ./release/
          done
          tar cvzf ./haproxy-${{ steps.clone.outputs.release_name }}.tar.gz release/
          ls -al release/

      - name: Dump binary info
        id: info
        run: |
          release\haproxy.exe -vv
          ldd release\haproxy.exe
          echo '```' > infoDump.txt
          release\haproxy.exe -vv >> infoDump.txt
          echo '```' >> infoDump.txt
          echo '```' >> infoDump.txt
          ldd release\haproxy.exe >> infoDump.txt
          echo '```' >> infoDump.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.clone.outputs.release_name }}
          tag_name: ${{ steps.clone.outputs.release_name }}
          target_commitish: ${{ github.sha }}
          body_path: infoDump.txt
          files: |
            *.tar.gz
